# -*- mode: sh -*-
################################################################################
#
# ZSH Setup
#
################################################################################
if [ "${DEBUG-no}" != "no" ]; then
  print "DEBUG: Loading /Users/tyalexander/.zshrc"
fi

ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.oh-my-zsh-custom
ZSH_THEME=risto

# Use red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Disable auto correction
DISABLE_CORRECTION="true"

# Disable autosetting terminal title for itab/ititle/iboth
DISABLE_AUTO_TITLE="true"

# activate highlighters
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

fpath=(/usr/local/share/zsh-completions $fpath)

# Load plugings (see  ~/.oh-my-zsh/plugins/* and ${ZSH_CUSTOM}/plugins/)
#plugins=(personalize ant brew brew-cask bundler colorize cp docker fabric go golang gem gitfast git github gradle grails history jsontools knife mvn npm osx perl pip pyenv pylint python rails rake rbenv redis-cli rsync ruby scala screen ssh-agent sudo tmux urltools thor urlstools vagrant virtualenv web-search)
plugins=(personalize ant brew brew-cask colorize cp docker fabric go golang gem history jsontools knife osx perl pip pyenv pylint python rails rake rbenv redis-cli rsync ruby ssh-agent sudo urltools thor vagrant virtualenv web-search zsh-syntax-highlighting sendgrid)

source $ZSH/oh-my-zsh.sh
