(provide 'php-util)
(require 'php-util)

(defun ilia-new-testcase()
  (interactive)
  (let ((indent "\t")
	(startedit 0))
    (insert "\n" indent "/**\n")
    (insert indent " * This test case tests that XXXX\n")
    (insert indent " */\n")
    (insert indent "public function test")
    (insert "XXXX")
    (insert "\n" indent "{" "\n" indent "\t")
    (setq startedit (point))
    (insert "\n" indent "}")
    (goto-char startedit)))

(defun pre-it-up()
  (interactive)
  (c-indent-command)
  (insert "echo \"\\n<pre>\\n\";\n")
  (c-indent-command)
  (insert "var_dump( ")
  (push-mark)
  (insert " );\n")
  (c-indent-command)
  (insert "echo \"</pre>\\n\";")
  (c-indent-command)
  (insert "\nexit;")
  (c-indent-command)
  (goto-char (mark)))

(define-key php-mode-map (kbd "C-x p")  'pre-it-up)

